---
on:
  workflow_call:
    inputs:
      versions:
        description: Stringified JSON object listing target versions
        required: true
        type: string
jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(inputs.versions) }}
    steps:
      - uses: actions/checkout@v3
      - run: 'echo "You are on branch: $(git branch)" with version:  ${{ matrix.version }}'
