---
on:
  workflow_call:
    inputs:
      # inputs.check-lock: true
      check-lock:
        default: true
        description: 'Boolean: To check composer.lock file'
        required: false
        type: boolean
      # inputs.directory: .
      directory:
        default: .
        description: 'String: Directory where composer.json is located'
        required: false
        type: string
      # inputs.strict: false
      strict:
        default: false
        description: 'Boolean: Return a non-zero exit code for warnings as well as errors'
        required: false
        type: boolean

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-composer:
    env:
      ACTION_COMMAND: composer validate
    runs-on: ubuntu-latest
    steps:
      - if: ${{ ! inputs.check-lock }}
        name: --no-check-lock
        run: echo "ACTION_COMMAND=${{ env.ACTION_COMMAND }} --no-check-lock" >> $GITHUB_ENV

      - if: ${{ ! inputs.strict }}
        name: --strict
        run: echo "ACTION_COMMAND=${{ env.ACTION_COMMAND }} --strict" >> $GITHUB_ENV

      - run: echo -e "${ACTION_COMMAND}\n${{ env.ACTION_COMMAND }}"

      - run: echo "{}" > composer.json

      - uses: "docker://composer"
        with:
          args: ${{ env.ACTION_COMMAND }}

      - uses: "docker://composer"
        with:
          args: ${ACTION_COMMAND}
