---
on:
  workflow_call:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'echo "You are on branch: $(git branch)"'
      - run: echo "::set-output name=time::$(date)"
